HOST: http://www.foobar.com/

--- Hello API v2 ---
---
Greenhorn Example Hello world API
---

--
Simple hello world GET request
--
GET /
< 200
< Content-Type: application/json
{ "text": "hello world!" }