HOST: http://www.foobar.com/

--- Hello API v2 ---
---
Greenhorn Example Hello world API
---

--
Shopping Cart Resources
The following is a section of resources related to the shopping cart
--
List products added into your shopping-cart. (comment block again in Markdown)
GET /
< 200
< Content-Type: application/json
{ "text": "hello world!" }